### ISSUE TITLE
Move "pythonlibs" deps to module_utils

### ISSUE THREAD

**Issue by senorsmile** [zahodi/ansible-mikrotik#4]
This will allow NOT add ENV bars to define the path for shared modules.

This also requires Ansible >= 2.3.0

**Comment by amatamalas** [comment]
Hi, I was thinking on helping with this issue. We could use the module_utils configuration parameter to add the current pythonlibs as part of the Ansible modules utils path. Then it would be a matter of changing the imports for the mt_api and mt_common in the library and test directories. In order to simplify the testing and usage, a simple local ansible.cfg file would be enough. This way if you move the module somewhere else the only thing you have to do is to change the ansible.cfg file and if the modules goes into the Ansible official repository it will work straight away. What do you think about it?

**Comment by zahodi** [comment]
@amatamalas that should work. Feel free to submit a PR if you have something written up.

**Comment by amatamalas** [comment]
@zahodi Sure I will.
